{
 "title": "Application Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Access-logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number of Request (live)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (job)(count_over_time({job=\"apache_logs\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Number of Request Per hour",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"apache_logs\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total Number of Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (job) (count_over_time({job=\"apache_logs\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Number of connection",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(sum by (client_ip) (count_over_time({job=\"apache_logs\"}[$__range])))"
    }
   ]
  },
  {
   "title": "HTTP Method Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (method) (count_over_time({job=\"apache_logs\"}[$__range]))"
    }
   ]
  },
  {
   "title": "HTTP Hit path",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (path) (count_over_time({job=\"apache_logs\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (status) (count_over_time({job=\"apache_logs\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Client_IP Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (client_ip) (count_over_time({job=\"apache_logs\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Apache Access Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"apache_logs\"} |= ``"
    }
   ]
  },
  {
   "title": "Error-logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error status Per Mins",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 468 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"apache_errors11\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Error status Per Hours",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 606 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"apache_errors11\"}[1h]))"
      }
     ]
    },
    {
     "title": "Total Errors count",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 614 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"apache_errors11\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Errors code",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 622 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (error) (\r\n  count_over_time(\r\n    {job=\"apache_errors11\"}\r\n    |~ \"AH[0-9]{5}\"\r\n    | regexp `(?P<error>AH[0-9]{5})`\r\n  [$__range])\r\n)\r\n"
      }
     ]
    },
    {
     "title": "Errors Live Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 630 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"apache_errors11\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Laravel-logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Laravel Status Per Mins",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 469 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"laravel_logs11\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Laravel Status Per Hours",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 518 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"laravel_logs11\"}[1h]))"
      }
     ]
    },
    {
     "title": "Total Laravel counts",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 526 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"laravel_logs11\"}[$__range]))"
      }
     ]
    },
    {
     "title": "SQLState Errors",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 534 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"laravel_logs11\"} |~ \"SQLSTATE\" [$__range]))"
      }
     ]
    },
    {
     "title": "Exception Errors",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 534 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"laravel_logs11\"} |~ \"Exception\" [$__range]))"
      }
     ]
    },
    {
     "title": "400 Bad Request Error",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 542 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"laravel_logs11\"} |~ \"400 Bad Request\" [$__range]))"
      }
     ]
    },
    {
     "title": "Laravel Live Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 550 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"laravel_logs11\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Slow-Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Query Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 470 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"live_logs\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Slow Query Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 478 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"live_logs\"}[1h]))"
      }
     ]
    },
    {
     "title": "Total Slow Queries",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 486 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({job=\"live_logs\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Slow Query Logs",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 494 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"live_logs\"}\r\n| line_format \" query_time={{.query_time}} query={{.query}}\""
      }
     ]
    },
    {
     "title": "Slow Query Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 503 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"live_logs\"}"
      }
     ]
    }
   ]
  }
 ]
}