{
 "title": "MySQL Dashboard",
 "description": "The Dashboard display Visualization Data from MySQL Exporter configured with Prometheus Database",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,10m,30m,1h,6h,12h" },
   {
    "name": "host",
    "label": "Server",
    "query": {
     "query": "label_values(mysql_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall MySQL Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MYSQL Uptime",
   "type": "stat",
   "description": "uptime of a MySQL server",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=~\"$host\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "timeseries",
   "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_aborted_connects{instance=~\"$host\"}[5m]))",
     "legendFormat": "Aborted Connects (attempts)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_aborted_clients{instance=~\"$host\"}[5m]))",
     "legendFormat": "Aborted Clients (timeout)"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "timeseries",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_slow_queries{instance=~\"$host\"}[5m])",
     "legendFormat": "Slow Queries"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "description": "number of active client connections at the moment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=~\"$host\"}",
     "legendFormat": "Current Connections"
    }
   ]
  },
  {
   "title": "Clients Connections",
   "type": "stat",
   "description": "Max Clients Connections - Max Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections. \nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\nConnections is the number of connection attempts to the MySQL server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=~\"$host\"}",
     "legendFormat": "Max Used Connections"
    },
    {
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"}",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "Processes, Commands and Handlers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Top Command Counters",
   "type": "timeseries",
   "description": "Top Command Counters - The Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, rate(mysql_global_status_commands_total{instance=~\"$host\"}[$interval]) > 0) or topk(5, irate(mysql_global_status_commands_total{instance=~\"$host\"}[5m]) > 0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "timeseries",
   "description": "Handler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\nThis is in fact the layer between the Storage Engine and MySQL.\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_handlers_total{instance=~\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=~\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "InnoDB Buffer Pool",
   "type": "piechart",
   "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=~\"$host\"}",
     "legendFormat": "Buffer Memory Size"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Overall Mem Size" }
   ]
  },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "piechart",
   "description": "***System Memory***: Total Memory for the system.\\\n***InnoDB Buffer Pool Data***: InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.\\\n***TokuDB Cache Size***: Similar in function to the InnoDB Buffer Pool,  TokuDB will allocate 50% of the installed RAM for its own cache.\\\n***Key Buffer Size***: Index blocks for MYISAM tables are buffered and are shared by all threads. key_buffer_size is the size of the buffer used for index blocks.\\\n***Adaptive Hash Index Size***: When InnoDB notices that some index values are being accessed very frequently, it builds a hash index for them in memory on top of B-Tree indexes.\\\n ***Query Cache Size***: The query cache stores the text of a SELECT statement together with the corresponding result that was sent to the client. The query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time.\\\n***InnoDB Dictionary Size***: The data dictionary is InnoDB ‘s internal catalog of tables. InnoDB stores the data dictionary on disk, and loads entries into memory while the server is running.\\\n***InnoDB Log Buffer Size***: The MySQL InnoDB log buffer allows transactions to run without having to write the log to disk before the transactions commit.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=~\"$host\"}",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "mysql_global_status_buffer_pool_pages{instance=~\"$host\", state=\"data\"} * on(instance) mysql_global_status_innodb_page_size{instance=~\"$host\"}",
     "legendFormat": "Used Buffer Pool Size"
    }
   ]
  },
  { "title": "MySQL Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "MySQL Network Traffic",
   "type": "timeseries",
   "description": "MySQL Network Traffic\nMySQL Network Traffic - Here we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=~\"$host\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "rate(mysql_global_status_bytes_sent{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=~\"$host\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  }
 ]
}